### PR TITLE
Reindex fix

### LINKED ISSUE #88: Run qtumd with -reindex if necessary

### PR DESCRIPTION
**Pull request by dwalintukan**
#88

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -11,28 +10,25 @@ const opn = require('opn');
...
 const syncRouter = require('./route/sync');
 const apiRouter = require('./route/api');
-
 const startSync = require('./sync');
 
 const PORT = 5555;
 
+// Create log dir if needed
+const dir = config.LOG_PATH;
+if (!fs.existsSync(dir)){
```
Comment (frankobe) [inline src/index.js]: nit: existence check can be moved to logger module exports too

File: src/index.js [hunk 2]
```diff
@@ -45,7 +41,50 @@ server.on('after', (req, res, route, err) => {
   }
 });
 
-const startAPI = async () => {
+let qtumProcess;
+
+function startQtumProcess(reindex) {
+  // avoid using path.join for pkg to pack qtumd
+  const qtumdPath = `${path.dirname(__dirname)}/qtumd`;
```
Comment (frankobe) [inline src/index.js]: does this work under pkg?

File: src/index.js [hunk 3]
```diff
@@ -45,7 +41,50 @@ server.on('after', (req, res, route, err) => {
...
+    logger.debug(`qtumd output: ${data}`);
+  });
+
+  qtumProcess.stderr.on('data', (data) => {
+    logger.error(`qtumd failed with error: ${data}`);
+
+    if (data.includes('You need to rebuild the database using -reindex-chainstate to enable -logevents.')) {
+      // Clean old process first
+      qtumProcess.kill();
+      qtumProcess = null;
```
Comment (frankobe) [inline src/index.js]: do we need this?

File: src/index.js [hunk 4]
```diff
@@ -45,7 +41,50 @@ server.on('after', (req, res, route, err) => {
...
+
+      // Restart qtumd with reindex flag
+      setTimeout(() => {
+        logger.info('Reindexing Qtum blockchain');
+        startQtumProcess(true);
+      }, 1000);
```
Comment (frankobe) [inline src/index.js]: feel like qtumd exit takes longer, let use 3000 for safe

File: src/index.js [hunk 5]
```diff
@@ -45,7 +41,50 @@ server.on('after', (req, res, route, err) => {
...
+    logger.error(`qtumd failed with error: ${data}`);
+
+    if (data.includes('You need to rebuild the database using -reindex-chainstate to enable -logevents.')) {
+      // Clean old process first
+      qtumProcess.kill();
+      qtumProcess = null;
+
+      // Restart qtumd with reindex flag
+      setTimeout(() => {
+        logger.info('Reindexing Qtum blockchain');
```
Comment (frankobe) [inline src/index.js]: `Restart and reindex Qtum blockchain`, probably need show this line in console

File: src/index.js (hunk 1 above)
Comment (dwalintukan) [reply src/index.js]: done, moved to logger.js

File: src/index.js (hunk 2 above)
Comment (dwalintukan) [reply src/index.js]: fixed with discussed changes

File: src/index.js (hunk 3 above)
Comment (dwalintukan) [reply src/index.js]: I wanted to make sure the first instance is cleaned up just in case the user force closes the app. Not sure if there would be a race condition for `qtumProcess.kill()`. Was thinking there could be a possibility that this call to `kill()` is done before the `SIGINT`'s `kill()` is called.

Not really sure what happens if you call `kill()` twice.

File: src/index.js (hunk 5 above)
Comment (dwalintukan) [reply src/index.js]: changed to console.log

File: src/index.js (hunk 4 above)
Comment (dwalintukan) [reply src/index.js]: ok. will have to increase the start time for sync, API, and browser open to accommodate this.

File: package.json [hunk 6]
```diff
@@ -21,7 +21,7 @@
   "license": "ISC",
   "bin": "src/index.js",
   "pkg": {
-    "assets": "ui/"
+    "assets": "ui/, src/logs/"
```
Comment (frankobe) [inline package.json]: remove `src/logs/`

Comment (dwalintukan) [reply package.json]: done

File: src/index.js [hunk 7]
```diff
@@ -45,7 +34,59 @@ server.on('after', (req, res, route, err) => {
...
+      }, 3000);
+    } else {
+      // add delay to give some time to write to log file
+      setTimeout(() => {
+        process.exit();
+      }, 500);
+    }
+  });
+
+  qtumProcess.on('close', (code) => {
```
Comment (frankobe) [inline src/index.js]: move this inside func startQtumProcess

File: src/index.js [hunk 8]
```diff
@@ -45,7 +34,59 @@ server.on('after', (req, res, route, err) => {
   }
 });
 
-const startAPI = async () => {
+let qtumProcess;
```
Comment (frankobe) [inline src/index.js]: move this variable inside func startQtumProcess

File: src/index.js (hunk 3 above)
Comment (frankobe) [reply src/index.js]: @dwalintukan kill() send a signal to the process. After moving qtumprocess var inside the func, we can restart without problem

File: src/index.js (hunk 8 above)
Comment (dwalintukan) [reply src/index.js]: `qtumProcess` is used in separate method `exit()`

File: src/index.js (hunk 7 above)
Comment (dwalintukan) [reply src/index.js]: hm? it already is inside the func

Comment (frankobe) [reply src/index.js]: sorry, mistake

File: src/index.js (hunk 8 above)
Comment (frankobe) [reply src/index.js]: lets try remove `qtumProcess.kill();` from exit(). The reason is that exit of parent process should kill childprocess. `qtumProcess = None` doesnt mean anything, variable reassignment can't guarantee the exit of the process.

Comment (dwalintukan) [reply src/index.js]: sounds good
